/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TORI106 (https://sketchfab.com/TORI106)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m4a1-33107f38b23c45cc8103768c0e961cdf
Title: M4A1
*/
/* eslint-disable */
// @ts-ignore
import { useGLTF } from '@react-three/drei';

export function WeaponModel(props) {
  const { nodes, materials } = useGLTF('/m4a1.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[36.502, -180.5, -0.676]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={28.703}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder006_M4-1_0']['geometry']}
            material={materials['M4-1']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder006_M4-2_0']['geometry']}
            material={materials['M4-2']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/m4a1.glb');
