/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kaan (https://sketchfab.com/KaansArsenal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-hk-mp510-cee1e02cc0664578bf2740ff926fe06b
Title: Low-Poly HK MP5/10
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WeaponModel(props) {
  const { nodes, materials } = useGLTF("/weapon.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.084, 0.47, -0.183]}
        rotation={[Math.PI / 2, 0, Math.PI + Math.PI / 2]}
        scale={0.038}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.transp}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/weapon.glb");
